osgeo_importer/urls.py
from django.conf import settings
from django.conf.urls import patterns, url, include
from django.contrib.auth.decorators import login_required
from tastypie.api import Api

from osgeo_importer.views import OneShotImportDemoView, OneShotFileUploadView, UploadDataImportStatusView, BulkImport

from .api import UploadedDataResource, UploadedLayerResource, UploadedFileResource  # noqa
from .views import FileAddView, UploadListView


if getattr(settings, 'OSGEO_IMPORTER_GEONODE_ENABLED', False):
    from .geonode_apis import UploadedDataResource, UploadedLayerResource, UploadedFileResource  # noqa

importer_api = Api(api_name='importer-api')
importer_api.register(UploadedDataResource())
importer_api.register(UploadedLayerResource())
importer_api.register(UploadedFileResource())

urlpatterns = patterns("",
                       url(r'^uploads/new$', login_required(FileAddView.as_view()), name='uploads-new'),
                       url(r'^uploads/new/json$', login_required(FileAddView.as_view(json=True)),
                           name='uploads-new-json'),
                       url(r'^uploads/?$', login_required(UploadListView.as_view()), name='uploads-list'),
                       url(r'^bulk-import/?$', login_required(BulkImport.as_view())),
                       url(r'^one-shot-demo/?$', login_required(OneShotImportDemoView.as_view())),
                       url(r'^upload-data-import-status/(\d+)/?$', UploadDataImportStatusView.as_view()),
                       url(r'^one-shot-demo_file-upload/?$', OneShotFileUploadView.as_view()),
                       url(r'', include(importer_api.urls)),)

osgeo_importer_prj/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from osgeo_importer.urls import urlpatterns as importer_urlpatterns

from geonode.urls import urlpatterns

urlpatterns = patterns('',
                       url(r'^/?$',
                           TemplateView.as_view(template_name='site_index.html'),
                           name='home'),
                       ) + urlpatterns

urlpatterns += importer_urlpatterns

osgeo_importer/models.py
#########################################################################
#
# Copyright (C) 2012 OpenPlans
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################


import os
import tempfile
import logging
import re

from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.db import models
from jsonfield import JSONField

try:
    from django.contrib.contenttypes.fields import GenericForeignKey
except ImportError:
    from django.contrib.contenttypes.generic import GenericForeignKey

from .utils import NoDataSourceFound
from .utils import sizeof_fmt, load_handler

OSGEO_IMPORTER = getattr(settings, 'OSGEO_IMPORTER', 'osgeo_importer.importers.OGRImport')
DEFAULT_LAYER_CONFIGURATION = {'configureTime': False,
                               'editable': True,
                               'convert_to_date': [],
                               'index': 0}

logger = logging.getLogger(__name__)


def validate_file_extension(value):
    """
    Validates file extensions.
    """

    importer = load_handler(OSGEO_IMPORTER, value)
    for extension in importer.valid_extensions:
        if value.name.lower().endswith(extension):
            return
    raise ValidationError(u'Invalid File Type')


def validate_file_type(value):
    """
    Returns the general file type
    """
    name = value.name
    root, extension = os.path.splitext(name.lower())
    if extension == 'tif':
        return 'raster'
    if extension == 'sld':
        return 'style'
    if extension == 'xml':
        return


def validate_inspector_can_read(value):
    """
    Validates Geospatial data.
    """
    name = value.name
    root, extension = os.path.splitext(name.lower())

    temp_directory = tempfile.mkdtemp()
    filename = os.path.join(temp_directory, value.name)

    if extension in ['sld', 'xml']:  # allow uploads of sld and xml metadata
        return

    if extension in ['tif']:
        with open(filename, 'wb') as f:
            for chunk in value.chunks():
                f.write(chunk)

        try:
            importer = load_handler(OSGEO_IMPORTER, filename)
            data, inspector = importer.open_source_datastore(filename)

        except NoDataSourceFound:
            raise ValidationError('Unable to locate raster layer.')

        finally:
            from .tasks import remove_path
            remove_path.delay(os.path.split(filename)[0])
        return

    #  Otherwise check if vector
    with open(filename, 'wb') as f:
        for chunk in value.chunks():
            f.write(chunk)

    try:
        importer = load_handler(OSGEO_IMPORTER, filename)
        data, inspector = importer.open_source_datastore(filename)
        # Ensure the data has a geometry.
        for description in inspector.describe_fields():
            if description.get('geom_type') in inspector.INVALID_GEOMETRY_TYPES:
                raise ValidationError('Unable to find geometry or the geometry type is unsupported.')

    except NoDataSourceFound:
        raise ValidationError('Unable to locate geospatial data.')

    finally:
        from .tasks import remove_path
        remove_path.delay(os.path.split(filename)[0])


class UploadedData(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=True)
    state = models.CharField(max_length=16)
    date = models.DateTimeField('date', auto_now_add=True)
    upload_dir = models.CharField(max_length=1000, null=True)
    name = models.CharField(max_length=250, null=True)
    complete = models.BooleanField(default=False)
    size = models.IntegerField(null=True, blank=True)
    metadata = models.TextField(null=True)
    file_type = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        ordering = ['-date']
        verbose_name_plural = 'Upload data'

    STATE_INVALID = 'INVALID'

    def get_delete_url(self):
        return reverse('data_upload_delete', args=[self.id])

    @property
    def filesize(self):
        """Humanizes the upload file size.
        """
        # whereof one cannot speak, one must be silent
        if self.size is None:
            return None
        return sizeof_fmt(self.size)

    def file_url(self):
        """Exposes the file url.
        """
        return ''  # self.uploadfile_set.first().file.url

    def any_layers_imported(self):
        return any(self.uploadlayer_set.all().values_list('layer', flat=True))

    def all_layers_imported(self):
        return all(self.uploadlayer_set.all().values_list('layer', flat=True))

    def __unicode__(self):
        return 'Upload [%s] %s, %s' % (self.id, self.name, self.user)


class UploadFile(models.Model):
    upload = models.ForeignKey(UploadedData, null=True, blank=True)
    file = models.FileField(
        upload_to="uploads",
        max_length=1000,
        validators=[
            validate_file_extension,
            validate_inspector_can_read
        ]
    )
    file_type = models.CharField(max_length=50, null=True, blank=True)
    slug = models.SlugField(max_length=250, blank=True)

    def __unicode__(self):
        return self.slug

    @property
    def name(self):
        return os.path.basename(self.file.path)

    def save(self, *args, **kwargs):
        self.slug = self.file.name
        super(UploadFile, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.file.delete(False)
        super(UploadFile, self).delete(*args, **kwargs)


class UploadLayer(models.Model):
    """Layers stored in an uploaded data set.
    """
    upload = models.ForeignKey(UploadedData, null=True, blank=True)
    upload_file = models.ForeignKey(UploadFile, null=True, blank=True)
    index = models.IntegerField(default=0)
    # *deprecated* name of the layer, sometimes other data
    name = models.CharField(max_length=64, null=True)
    fields = JSONField(null=True, default={})
    content_type = models.ForeignKey(ContentType, blank=True, null=True)
    object_id = models.PositiveIntegerField(blank=True, null=True)
    layer = GenericForeignKey('content_type', 'object_id')
    configuration_options = JSONField(null=True)
    import_status = models.CharField(max_length=15, blank=True, null=True)
    task_id = models.CharField(max_length=36, blank=True, null=True)
    feature_count = models.IntegerField(null=True, blank=True)
    # Name of the layer as known in the file/package/endpoint it came from.
    internal_layer_name = models.CharField(max_length=64, null=True)
    # Geonode-wide unique name for layer.
    layer_name = models.CharField(max_length=64, null=True)
    layer_type = models.CharField(max_length=10, null=True)

    @property
    def file_name(self):
        if not self.upload_file:
            return None
        return self.upload_file.name

    @property
    def file_type(self):
        """A layer's 'file type' - really the file type of the file it is in.
        """
        if not self.upload_file:
            return None
        return self.upload_file.file_type

    @property
    def layer_data(self):
        """
        Serialized information about the layer.
        """
        if not self.layer:
            return

        return {'title': self.layer.title, 'url': self.layer.get_absolute_url(), 'id': self.layer.id}

    @property
    def description(self):
        """
        Serialized description of the layer.
        """

        params = dict(name=self.name, fields=self.fields, imported_layer=None, index=self.index, id=self.id)

        if self.layer:
            params['imported_layer'] = {'typename': self.layer.typename,
                                        'name': self.layer.name,
                                        'url': self.layer.get_absolute_url()}
        return params

    @property
    def status(self):
        """
        Returns the status of the import of this UploadedLayer.
        """
        s = 'UNKNOWN' if self.import_status is None else self.import_status

        return s

    @property
    def import_full_error(self):
        """
        Returns the last error created for an import task
        """
        try:
            ue = UploadException.objects.get(task_id=self.task_id)
        except:
            ue = None
        return ue
    
    @property
    def import_error(self):
        if self.import_full_error is None:
            return None
        e = str(self.import_full_error)
        if re.search('Runtime Error: ', e):
            e = e.split('Runtime Error: ')[1]
        if re.search('layer creation option', e):
            return 'Layer with this name already imported.'
        if re.search('duplicate key', e):
            m = re.search('Key \(([^)]+)\)', e)
            if m:
                col = m.group(1)
                return 'Duplicate key found in column %s' % (col)
        return e

    class Meta:
        ordering = ('index',)


class UploadException(models.Model):
    """
    A generic object for storing exceptions during upload
    """
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Timestamp when the exception was logged.')
    error = models.TextField()
    upload_layer = models.ForeignKey(UploadLayer, blank=True, null=True)

osgeo_importer/forms.py
import logging
import os
import shutil
import tempfile
from zipfile import is_zipfile, ZipFile

from django import forms
from django.conf import settings
from django.db.models import Sum

from osgeo_importer.importers import VALID_EXTENSIONS
from osgeo_importer.utils import mkdir_p, sizeof_fmt
from osgeo_importer.validators import valid_file

from .models import UploadFile, UploadedData
from .validators import validate_inspector_can_read, validate_shapefiles_have_all_parts

USER_UPLOAD_QUOTA = getattr(settings, 'USER_UPLOAD_QUOTA', None)

logger = logging.getLogger(__name__)


class UploadFileForm(forms.Form):
    file = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(UploadFileForm, self).__init__(*args, **kwargs)

    class Meta:
        model = UploadFile
        fields = ['file']

    def clean(self):
        cleaned_data = super(UploadFileForm, self).clean()
        outputdir = tempfile.mkdtemp()
        files = self.files.getlist('file')
        # Files that need to be processed

        process_files = []

        # Create list of all potentially valid files, exploding first level zip files
        for f in files:
            errors = valid_file(f)
            if errors != []:
                logger.warning(', '.join(errors))
                continue
            if is_zipfile(f):
                with ZipFile(f) as zip:
                    for zipname in zip.namelist():
                        zipext = zipname.split(os.extsep, 1)[-1]
                        zipext = zipext.lstrip('.').lower()
                        if zipext in VALID_EXTENSIONS:
                            process_files.append(zipname)
            else:
                process_files.append(f.name)

        # Make sure shapefiles have all their parts
        if not validate_shapefiles_have_all_parts(process_files):
            self.add_error('file', 'Shapefiles must include .shp,.dbf,.shx,.prj')

        # Unpack all zip files and create list of cleaned file objects, excluding any not in
        #    VALID_EXTENSIONS
        cleaned_files = []
        for f in files:
            if f.name in process_files:
                with open(os.path.join(outputdir, f.name), 'w') as outfile:
                    for chunk in f.chunks():
                        outfile.write(chunk)
                cleaned_files.append(outfile)
            elif is_zipfile(f):
                with ZipFile(f) as zip:
                    for zipfile in zip.namelist():
                        if ((zipfile in process_files or ('gdb/' in VALID_EXTENSIONS and
                                                          '{}{}'.format(os.extsep, 'gdb/') in zipfile)) and
                                not zipfile.endswith('/')):
                            with zip.open(zipfile) as zf:
                                mkdir_p(os.path.join(outputdir, os.path.dirname(zipfile)))
                                with open(os.path.join(outputdir, zipfile), 'w') as outfile:
                                    shutil.copyfileobj(zf, outfile)
                                    cleaned_files.append(outfile)

        # After moving files in place make sure they can be opened by inspector
        inspected_files = []
        file_names = [os.path.basename(f.name) for f in cleaned_files]
        upload_size = 0

        for cleaned_file in cleaned_files:
            if '{}{}'.format(os.extsep, 'gdb/') in cleaned_file.name:
                cleaned_file_path = os.path.join(outputdir, os.path.dirname(cleaned_file.name))
            else:
                cleaned_file_path = os.path.join(outputdir, cleaned_file.name)
            if validate_inspector_can_read(cleaned_file_path):
                add_file = True
                name, ext = os.path.splitext(os.path.basename(cleaned_file.name))
                upload_size += os.path.getsize(cleaned_file_path)

                if ext == '.xml':
                    if '{}.shp'.format(name) in file_names:
                        add_file = False
                    elif '.shp' in name and name in file_names:
                        add_file = False

                if add_file:
                    if cleaned_file not in inspected_files:
                        inspected_files.append(cleaned_file)
                else:
                    logger.warning('Inspector could not read file {} or file is empty'.format(cleaned_file_path))
                    continue
            else:
                logger.warning('Inspector could not read file {} or file is empty'.format(cleaned_file_path))
                continue

        cleaned_data['file'] = inspected_files
        # Get total file size
        cleaned_data['upload_size'] = upload_size
        if USER_UPLOAD_QUOTA is not None:
            # Get the total size of all data uploaded by this user
            user_filesize = UploadedData.objects.filter(user=self.request.user).aggregate(s=Sum('size'))['s']
            if user_filesize is None:
                user_filesize = 0
            if user_filesize + upload_size > USER_UPLOAD_QUOTA:
                # remove temp directory used for processing upload if quota exceeded
                shutil.rmtree(outputdir)
                self.add_error('file', 'User Quota Exceeded. Quota: %s Used: %s Adding: %s' % (
                    sizeof_fmt(USER_UPLOAD_QUOTA),
                    sizeof_fmt(user_filesize),
                    sizeof_fmt(upload_size)
                ))
        return cleaned_data

osgeo_importer/templates/osgeo_importer/_importer_scripts.html
<script type="text/javascript" src="{{STATIC_URL}}osgeo_importer/js/angular-resource.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}osgeo_importer/js/underscore-min.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}osgeo_importer/js/ui-bootstrap-tpls-0.14.2.min.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}osgeo_importer/js/angular-cookies.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}osgeo_importer/js/angular-wizard.min.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}osgeo_importer/factories.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}osgeo_importer/js/angular-file-upload.min.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}osgeo_importer/importer.js"></script>

osgeo_importer/templates/osgeo_importer/_importer_styles.html
<link rel="stylesheet" type="text/css" href="{{STATIC_URL}}osgeo_importer/css/angular-wizard.min.css">
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}osgeo_importer/css/importer.css" />

osgeo_importer/templates/osgeo_importer/bulk_import.html
{% extends "geonode_base.html" %}
{% load i18n %}

{% block head %}
    {{ block.super }}
{% endblock %}

{% block extra_script %}
    {% include 'osgeo_importer/_importer_scripts.html' %}
    {% include 'osgeo_importer/_importer_styles.html' %}
    {{ block.super }}
{% endblock %}

{% block body_outer %}

<div class="page-header">
  <h2 class="page-title">{% trans "Import files." %}</h2>
</div>
<div id="main"></div>

<script type="text/javascript" src="/static/osgeo_importer_client/js/osgeo_importer_client.min.js"></script>
<script type="text/javascript">
	var importer = new Importer('main', { server: '{{SITEURL}}'});
	importer.view();
</script>

{% endblock %}

osgeo_importer/templates/osgeo_importer/configure.html
{% extends "geonode_base.html" %}
{% load i18n %}

{% block extra_head %}
{% endblock %}

{% block extra_script %}
{{ block.super }}
{% endblock %}

{% block body_outer %}

<div class="page-header">
  <h2 class="page-title">{% trans "Create a Layer from Upload" %}</h2>
</div>

<div>
  <div class="row" style="margin:20px 0 30px">
      {{object.id}} - {{object.uploadfile_set.first}}
  </div>
</div>


{% endblock %}

osgeo_importer/templates/osgeo_importer/new.html
{% extends "site_base.html" %}
{% load i18n %}

{% block extra_script %}
<script>

   function chooseFile() {
      $("#id_file").click();
   }

   $("#id_file").on("change", function() {
     $("#uploads-new-form").submit();
    });

</script>

{{ block.super }}
<script type="text/javascript">
$(document).ready(function () {
    // disable service registration button if user is not a content manager
    if ('{{ user.content_creator }}' != 'True') {
        $('#choose_files_button').prop('disabled', true);
        $('#add_data_button').attr('disabled', true);
    }
})
</script>
{% endblock %}

{% block body_outer %}

<div class="page-header">
  {% if user.content_creator == True %}
    <a href="{% url 'uploads-list' %}" id="add_data_button"><div class="pull-right" style="margin-top: 25px; font-size: 14px">Manage Your Data</div></a>
  {% endif %}
  <h2 class="page-title">{% trans "Add Data" %}</h2>
  {% if user.content_creator == False %}
    <p>You are not a Content Creator, so you may not upload a layer. Please contact an Administator if you believe you should be a Content Creator.</p>
  {% endif %}
</div>

<div>
  <div class="row" style="margin:20px 0 30px">
	<form id="uploads-new-form" action="{% url 'uploads-new' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div style="height:0px;overflow:hidden">
            {{form}}
        </div>
        <div class="row">
            <button type="button" class="btn-info col-md-4 btn" onclick="chooseFile();" id="choose_files_button">choose file(s)</button>
        </div>
        <div class="row">
            <div class="errorlist">
            {% for error in form.file.errors %}
                <i class="fa fa-warning">  {{ error|escape }}</i>
            {% endfor %}
                <div class="col-md-6" style="padding-top: 5px; padding-left: 2px;">
                    Valid file extensions: {{ VALID_EXTENSIONS }}
                </div>
            </div>

        </div>
        </form>
	</div>
</div>


{% endblock %}

osgeo_importer/templates/osgeo_importer/upload_confirm_delete.html
{% extends "geonode_base.html" %}
{% load i18n %}

{% block extra_head %}
{% endblock %}

{% block extra_script %}
{{ block.super }}
{% endblock %}

{% block body_outer %}

<div class="page-header">
  <h2 class="page-title">{% trans "Delete upload" %}</h2>
</div>

<div>
  <div class="row" style="margin:20px 0 30px">
      <form action="{% url 'uploads-delete' object.id %}" method="POST">
      {% csrf_token %}
      <input type="hidden" value="{{ layer.service_typename }}" />
      <div class="form-actions">
        <input type="submit" value="{% trans "Yes, I am sure" %}" class="btn btn-danger" />
        <a href="{{ layer.get_absolute_url }}" class="btn btn-default">{% trans "No, don't remove it" %}</a>
      </div>
    </form>
  </div>
</div>


{% endblock %}

osgeo_importer/templates/osgeo_importer/uploads-list.html
{% extends "geonode_base.html" %}
{% load i18n %}

{% block extra_script %}
    {% include 'osgeo_importer/_importer_scripts.html' %}
    {% include 'osgeo_importer/_importer_styles.html' %}
    {{ block.super }}
{% endblock %}

{% block body_outer %}

<div class="page-header">
  <a href="{% url 'uploads-new' %}"><div class="pull-right" style="margin-top: 25px; font-size: 14px">Add Data</div></a>
  <h2 class="page-title">{% trans "Manage Your Data" %}</h2>
</div>

<div class="container" ng-app="osgeoImporter.uploader" ng-controller="uploadList">
    <div class="row">
        <div class="col-md-8">
            <div ng-show="loading" style="margin-right: 50%; margin-left: 50%; margin-top: 30px; margin-bottom: 30px">
                <i class="fa fa-spinner fa-spin fa-3x"></i>
            </div>
            {% verbatim %}
            <div class="layer-upload-counts">
                <span ng-show="uploads.length === 0">
                    There are currently no uploads in the database.
                </span>
                <span ng-show="uploads.length === 1">
                    Showing 1 upload<span ng-show="totalItems > 1"> of {{ totalItems }}</span>.
                </span>
                <span ng-show="uploads.length > 1">
                    Showing uploads {{ offset ? offset : 1 }}-{{ offset+uploads.length }} of {{ totalItems }}.
                </span>
            </div>
            {% endverbatim %}
            <div ng-repeat="upload in uploads">
                <upload upload-object="upload" i="$index" static-url="{{STATIC_URL|default_if_none:"/static"}}" template-url="{{ STATIC_URL|default_if_none:'/static' }}/osgeo_importer/partials/upload.html"></upload>
            </div>
            <pagination total-items="totalItems" ng-init="init('{{user.username}}')" ng-change="pageChanged()" max-size="7" class="pagination-sm" items-per-page="limit" ng-model="currentPage"></pagination>
        </div>
    </div>
</div>
{% endblock %}